data:
    dataset: "MVTec"
    category: "bottle"
    target_folder: "broken_large"
    use_mask: true
    use_target: false
    image_size: 256
    channels: 4
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 0

model:
    type: "simple"
    in_channels: 4
    out_ch: 4
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 4
    last_only: True

path:
    gt_mask_path: "Meta_Inspector/gt_mask/000_mask.png"